### ISSUE TITLE
A case where rowSds() doesn't give zero where sd() does

### ISSUE THREAD

**Issue by rcastelo** [HenrikBengtsson/matrixStats#204] opened 2021-06-03 15:29 UTC
Hi Henrik,

I've found a case in which `rowSds()` is giving a value that is practically zero but not exactly, while base `sd()` gives exactly zero. This is at the root of bug reported to one of my packages in this other [issue](https://github.com/rcastelo/GSVA/issues/54). Here is a minimal example reproducing the problem:

```
library(matrixStats)
x <- matrix(rep(1.1, 10), nrow=1, byrow=TRUE)
rowSds(x)
[1] 2.340556e-16
apply(x, 1, sd)
[1] 0
```
I know I can threshold on such a small value and set it to zero, but I wonder whether `rowSds()` should not give an exact zero just as the base `sd()` function.

Thanks!!

**Comment by HenrikBengtsson** [comment] 2021-06-03 20:11
Thanks for report.  Here's a tad small example, that operates on a contiguous vector (column based) and has a minimal number of elements (with 5, it returns 0):

```r
> colVars(rep(0.1, times=6), dim.=c(6,1))
[1] 2.311116e-34
```

I suspect this has to do with compiler and CPU optimization.  I think we've seen this for other types of calculations too, not just in matrixStats.  This would require some debugging to trace the intermediate results in the native code.

A workaround seems to be to specify the `center` argument, which will cause it to fall back to R code (at least for now):

```r
> x <- matrix(rep(0.1, times=6), nrow = 1L)
> mu <- rowMeans(x)
> rowVars(x, center=mu)
[1] 0
```

However, in the bigger picture, I don't think it's even safe to rely on `z == 0` when working with floating points.  Basically, results shouldn't go down different paths if you get 0 or epsilon.  For similar reasons, I don't think truncation at some random n*eps is a good idea either.  But I guess it depends on the model/estimator and what's practical.

**Comment by rcastelo** [comment] 2021-06-04 14:02
What would you recommend to filter out genes with constant expression (these are often bad for certain calculations because they introduce collinearities, etc.)?

**Comment by HenrikBengtsson** [comment] 2021-06-04 20:52
Sorry, I don't, and I'd say it's a really hard problem.  In the copy-number world, we see the same question, and even there, with truly discrete underlying states, it's a tricky question when you work with observations.  But I'd say the essence of the problem is to define what "constant expression" means and in what context. The way I think about this is roughly:

(1) The stringiest definition would be numerically constant (as in D(x,y) = 0 or D(x,y) <= eps), which then depend on technology, read depth, and so on.

(2) Then there's the problem of numerical stability you're having, which happens at some D(x, y) <= tau threshold, and tau probably depends on other data.  So that would be another definition.

(3) Then there's biological definition of constant expression, which is not clear to me what it even means, or even exists. But, I guess one could translate it to meaning no significant change, which then would translated to another D(x, y) <= gamma threshold.  OTH, that might be what you're after in the first place, so such a threshold might bias your results.

So, after all this yada yada of mine, using D(x, y) <= tau for some tuning parameter 'tau' might be good enough for your problem of numerical stability. But, I think using tau=0 is asking for problems (like the one you ran into here). I suspect using tau=eps for some very small eps, e.g. `eps = .Machine$double.eps`, is also risky.

**Comment by rcastelo** [comment] 2021-06-05 16:19
Thanks Henrik for taking the time to share your views on this, I see that the problem is harder than I initially thought. Going back to this specific issue, what do you think should be the goal for `rowSds()` with this edge case? Should it behave like base `sd()` for consistency? Otherwise, we might as well close this issue.

**Comment by HenrikBengtsson** [comment] 2021-06-06 00:44
Yes, ideally `rowVars()` should give the same numerical results as `vars()` (the sd estimators are just sqrt(var) at the end). Let's keep it open until investigated and understood what causes the difference. The outcome might be a fix or, if not possible to fix, a mentioning in the documentation.

**Comment by HenrikBengtsson** [comment] 2023-05-27 03:55
This has been fixed in the develop version by introducing `refine = TRUE`, which will cause the sample means to be estimated using a two-pass scan for higher precision, which gives higher precision for the variance estimate, e.g.

```r
> library(matrixStats)
> x <- matrix(rep(1.1, 10), nrow=1, byrow=TRUE)
> rowSds(x, refine = TRUE)  # default
[1] 0
> rowSds(x, refine = FALSE)
[1] 2.340556e-16
> apply(x, MARGIN = 1L, FUN = sd) - rowSds(x)
[1] 0
```

**Closed by HenrikBengtsson** 2023-05-27 03:55 UTC
