### ISSUE TITLE
weightedMad error with NA in w

### ISSUE THREAD

**Issue by wmk925** [HenrikBengtsson/matrixStats#154] opened 2019-08-21 14:13 UTC
weightedMad:
When passing a vector of weights that include at least one NA, the following if statement throws an error since the result of !all(tmp) is NA instead of T/F:
`tmp <- (w > 0)
    if (!all(tmp)) {
        x <- .subset(x, tmp)
        w <- .subset(w, tmp)
        n <- length(x)
    }`
Perhaps the following if statement should be performed first.
`tmp <- NULL
    if (na.rm) {
        keep <- which(!is.na(x) & !is.na(w))
        x <- .subset(x, keep)
        w <- .subset(w, keep)
        n <- length(x)
        keep <- NULL
    }
    else if (anyMissing(x)) {
        return(na_value)
    }`

**Comment by HenrikBengtsson** [comment] 2019-08-21 14:16
Thanks. Duplicate of Issue #140. Fixed in next release.

**Closed by HenrikBengtsson** 2019-08-21 14:16 UTC

**Comment by wmk925** [comment] 2019-08-21 14:44
My apologies, I didn't search for weightedVar (but should have). Great
package!
-Wes
